categoryId: 1774 # CATEGORY NAME
name: Application model modularity
questions:
  - description: 1 What is a model?
    choices:
      - one class inheriting from more super classes
      - more classes inheriting from one super class
      - NULL
      - NULL
    hint: First think about the definistion for inheritance
    explanation: >-
      Inheritance is inheriting from one super class, therefore multiple
      inheritance is inheriting from more superclass
    correctChoice: 0 
  - description: 2 What is an application 
    choices:
      - one class inheriting from more super classes
      - more classes inheriting from one super class
      - more classes inheriting from more super classes
      - NULL
    hint: First think about the definistion for inheritance
    explanation: >-
      Inheritance is inheriting from one super class, therefore multiple
      inheritance is inheriting from more superclass
    correctChoice: 0 
  - description: '3 The default value of a static integer variable of a class in Java is:'
    choices:
      - '0'
      - '1'
      - garbage value
      - 'null'
    hint: hint not applicable to this question
    explanation: The correct choice is 0. Since this is defined by Java.
    correctChoice: 0
  - description: 4 Which statement is not true in java language?
    choices:
      - A public member of a class can be accessed in all the packages.
      - >-
        A private member of a class cannot be accessed by the methods of the
        same class.
      - A private member of a class cannot be accessed from its derived class.
      - A protected member of a class can be accessed from its derived class.
    hint: the class dependence concept is similar to that of C language
    explanation: >-
      Private member of the same class can still be accessed by the methods in
      the same class
    correctChoice: 1
  - description: 5 Which statement is not true in java language?
    choices:
      - A public member of a class can be accessed in all the packages.
      - >-
        A private member of a class cannot be accessed by the methods of the
        same class.
      - A private member of a class cannot be accessed from its derived class.
      - A protected member of a class can be accessed from its derived class.
    hint: the class dependence concept is similar to that of C language
    explanation: >-
      Private member of the same class Ocan still be accessed by the methods in
      the same class
    correctChoice: 1
